### ISSUE TITLE
Lesson 1: Syntax

### ISSUE THREAD

**Issue by Leandros** [cpp-tour/cpp-tour#13]
Please use this ticket for discussions about **Lesson 1: Syntax**

**Comment by grisumbras** [comment]
I don't really understand, what should go here. The basic "semicolon ends a statement, curly braces mark borders of scope"? I think, it's better to introduce syntactic constructs one by one together with code that uses them.

**Comment by Leandros** [comment]
_shrug_

Let's close it, than.
