### ISSUE TITLE
Build and test code snippets

### ISSUE THREAD

**Issue by grisumbras** [cpp-tour/cpp-tour#16]
We should organize some testing for code snippets. Webpack has a plugin the allows to run arbitrary shell commands ([webpack-shell-plugin](https://www.npmjs.com/package/webpack-shell-plugin)), I suggest we'll use it with a C++-aware build system. For maximum convenience for the community I suggest CMake.

So, this is the layout I propose:
```
/
└── lessons
    ├── CMakeLists.txt
    ├── x.y-TitleXY
    │   ├── CMakeLists.txt
    │   └── code.cpp
    └── a.b-TitleAB
        ├── CMakeLists.txt
        └── code.cpp
```

That way each lesson's directory encapsulates required test (we should test what the compiled snippet returns/outputs).

**Comment by Leandros** [comment]
Structure looks good to me!

**Comment by DoumanAsh** [comment]
@grisumbras For simplicity sake wouldn't it be fine to have on CMakeLists that uses recursive glob on cpp files?

**Comment by grisumbras** [comment]
It would be less files, but not necessarily simpler: different files may require different tests, we may use _several_ source files for some lessons.

**Comment by Leandros** [comment]
I agree with @grisumbras, there will be later lessons where there might be multiple source files. 
Oh, @grisumbras, where would you define the actual test? In `CMakeLists.txt`? How would we specify that we expect a return value of `0` and `foo` printed to stdout?

**Comment by grisumbras** [comment]
There is a test property in CMake that allows matching test output against a regexp. If checking status is necessary, then we'll have to write a wrapping script (possibly in CMake language) that runs the program and checks its output.
