### ISSUE TITLE
Design (incl. mockup)

### ISSUE THREAD

**Issue by Leandros** [cpp-tour/cpp-tour#19]
I've prepared a quick mockup of how the first version of the tour could look like:

![design](https://user-images.githubusercontent.com/396475/33762502-f0af0c7c-dc0c-11e7-9de4-357c7a4cc096.png)

**Comment by grisumbras** [comment]
LGTM

**Comment by lmapii** [comment]
looking forward to it :) any plans on going into detail about a matching build environment (MAKE, CMAKE or ninja)?

**Comment by Leandros** [comment]
@imapii Yes, if you look at #7, you'll see a mention of build systems.

**Comment by arnemertz** [comment]
Looks good, but probably will need a different option for mobile.
