### ISSUE TITLE
Code Editor

### ISSUE THREAD

**Issue by Leandros** [cpp-tour/cpp-tour#2]
Scope
- [ ] Crtl-Enter to run code #23
- [ ] Vim mode for editor.
- [ ] Use tab? to focus on editor
- [ ] Allow to configure compiler through editor

**Comment by DoumanAsh** [comment]
For now we're going to use [CodeMirror](https://codemirror.net/) #8

**Comment by Leandros** [comment]
Features I'd like to have in the future:

- Ctrl-Clicking (or right-click, if a browser does not allow ctrl-click) on a known function should open inline documentation, with a link to CppReference


We should evaluate whether they're possible, or determine the required amount of work for implementing them.

**Comment by Leandros** [comment]
Another feature I've noticed we need: line numbers!

**Comment by qacwnfq** [comment]
It would be nice if you could enable CodeMirrors vim bindings from some sort of menu.
