### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by Leandros** [cpp-tour/cpp-tour#20]
Two super simple logo mockups. Which one do you prefer?

(Vote by "Thumbs Up" the post with the logo inside)

**Got a great idea for a logo? Feel free to post your idea here!**

**Comment by Leandros** [comment]
![tourlogo](https://user-images.githubusercontent.com/396475/33767122-afe8928a-dc20-11e7-8aec-e146392e915c.png)

**Comment by Leandros** [comment]
![tourlogo2](https://user-images.githubusercontent.com/396475/33767197-f7e97086-dc20-11e7-8b47-26064082b445.png)

**Comment by adishavit** [comment]
Here's an idea. Not final - just a concept. 
![image](https://user-images.githubusercontent.com/1814800/33787645-de43980e-dc76-11e7-83c4-599a378cd61b.png)

**Comment by qacwnfq** [comment]
Nice logos. I like the second the most. It has pretty colors, a good font and is simple. The ratio between height and width is also good. You can put it anywhere and it will look good.

**Comment by AsmCoder110** [comment]
![cpp-tour](https://user-images.githubusercontent.com/16755893/33802566-2201aefe-dd72-11e7-9e25-a75fe23a1108.png)

**Comment by adishavit** [comment]
![image](https://user-images.githubusercontent.com/1814800/33808357-834985b2-dded-11e7-8132-c47821f485ad.png)

(SVG available)
Rational: looks like a map/navigation pin - implies landmarks on a _TOUR_...
(also keeps ISO C++ logo colors and feel, but avoid ripping it off completely).

![image](https://user-images.githubusercontent.com/1814800/33808362-89371bc4-dded-11e7-980e-167e7f4d8314.png)

**Comment by Deveroux** [comment]
I like the fact that the logo is that of the ISO C++ site. Is this a joint effort with the committee? Also, given that Bjarne had previously published a book called "A Tour of C++", I wonder if the choice of naming my create some confusion.
