### ISSUE TITLE
Add Ctrl-Enter shortcut to run code

### ISSUE THREAD

**Issue by Leandros** [cpp-tour/cpp-tour#23]
The editor used is CodeMirror. It should, when selected and Ctrl-Enter is pressed run the code.

**Comment by unreadable** [comment]
I can definitely help with this and I will. What about opening a frontend issues thread to list there things that should get done?
Edit: Ctrl + E will target google search bar, it would be better to find another keys combo..

**Comment by Leandros** [comment]
@unreadable You can see all the things which needs to be done, by looking at all issues tagged [good first issue](https://github.com/Leandros/cpp-tour/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22).

If you want to tackle this, I'll block it. Send a PR once you're done. Thanks a ton for your help!

**Comment by unreadable** [comment]
Ok, sounds good. It's just a matter of a simple js script. What about Alt + C?

**Comment by Leandros** [comment]
What's wrong with Ctrl-Enter? Works for any other editor, why shouldn't it work for us?
