### ISSUE TITLE
Create the top bar

### ISSUE THREAD

**Issue by Leandros** [cpp-tour/cpp-tour#26]
The top bar, according to the design (#19) should have the logo (can be found in `src/images/logo_small.png`) on the left, the burger menu to open the side bar and the social media icons on the right.

## To Do

- [ ] burger menu
    - [ ] animation
- [x] social icons
- [ ] sidebar opening animation

**Comment by ghost** [comment]
We can use http://fontawesome.io/ for that. What you think?

**Comment by Leandros** [comment]
Sure! That should work. Just make sure the font actually only contains the required icons.
