### ISSUE TITLE
Parse lessons from rST into our site

### ISSUE THREAD

**Issue by Leandros** [cpp-tour/cpp-tour#9]
Lessons should be parsed from rST ([reStructuredText](http://docutils.sourceforge.net/rst.html)) into HTML pages. Should be linked in order in our sidebar and selectable. 

I propose the following file structure (assume `/` is the root of our repo):

```
/
└── lessons
    ├── 0.0-Introduction
    │   ├── code.cpp
    │   └── text.rst
    └── 1.0-HelloWorld
        ├── code.cpp
        └── test.rst

```

First digit being the chapter number, second digit the lesson number.

**Comment by Leandros** [comment]
We require a few specific features, to allow us to create powerful content:

- Footnotes (click / tap on the (1) here: https://arvid.io/2017/04/23/is-my-process-running-from-bash-exe-or-cmd-exe/) Done with [bigfoot.js](http://www.bigfootjs.com/).
- Inline documentation, similar to the code editor ([here](https://github.com/Leandros/cpp-tour/issues/2#issuecomment-349293895)) the content requires us to link to documentation. (Example: click on any function here: https://learnopengl.com/#!Advanced-OpenGL/Stencil-testing)
- Code snippets, with syntax highlighting. Also, each code snippet we present in the content should always be an excerpt to a fully working example which can be loaded into the editor on the right and directly executed.

**Comment by oliora** [comment]
Should not the site use [Jekyll](http://jekyllrb.com/) or even be fully hosted on github pages?
